### ISSUE TITLE
Workflow using config-checker returns ModuleNotFoundError

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/config-checker#66]
I tried to use config-checker in a workflow on precice-gen. I pasted in the workflow below. The main problem is that it returns:
```sh
| Traceback (most recent call last):
|   File "/mnt/c/Users/thore/Desktop/precice/Forschungsprojekt/precice-structure-generator/config-checker/preciceconfigchecker/cli.py", line 9, in <module>
|     from preciceconfigchecker.rules_processing import check_all_rules, print_all_results
|   File "/mnt/c/Users/thore/Desktop/precice/Forschungsprojekt/precice-structure-generator/venv/lib/python3.12/site-packages/preciceconfigchecker/rules_processing.py", line 8, in <module>
|     from preciceconfigchecker.rules import missing_coupling, missing_exchange, data_use_read_write, compositional_coupling
| ModuleNotFoundError: No module named 'preciceconfigchecker.rules'
```
It fails on the last step, where i cd into config-checker and try to call the CLI file. It is propably just me don't seeing the error, but if it is not my error I thought I would let you know.

The results you see were from my using `act` to test the workflows locally but they also fail on github: https://github.com/precice-forschungsprojekt/precice-generate/pull/109 (the failing check)

[Direct link to failing check:](https://github.com/precice-forschungsprojekt/precice-generate/actions/runs/14145756013/job/39632855627?pr=109)
--------------------
Full workflow:
```yml
name: Validate Example Configurations

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  discover-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone config-checker
      run: |
        git clone --recurse-submodules https://github.com/precice-forschungsprojekt/config-checker.git
        echo "Config-checker cloned to $(pwd)/config-checker"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies of precice-gen
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install .

    - name: Update package list
      run: |
        sudo apt-get update

    - name: Install preCICE
      run: |
        wget https://github.com/precice/precice/releases/download/v3.1.2/libprecice3_3.1.2_noble.deb
        sudo apt install -y ./libprecice3_3.1.2_noble.deb

    - name: Install dependencies of config-checker
      run: |
        source venv/bin/activate
        sudo apt install -y libopenmpi-dev
        python -m pip install --upgrade pip setuptools cython
        cd config-checker
        pip install .

    - name: Test CLI of precice-gen
      run: |
        source venv/bin/activate
        precice-gen --help

    - name: Test CLI of config-checker
      run: |
        source venv/bin/activate
        cd config-checker
        python preciceconfigchecker/cli.py
```
Full error:
```sh
[Validate Example Configurations/discover-and-test]   ✅  Success - Main Test CLI of precice-gen
[Validate Example Configurations/discover-and-test] ⭐ Run Main Test CLI of config-checker
[Validate Example Configurations/discover-and-test]   🐳  docker exec cmd=[bash -e /var/run/act/workflow/8] user= workdir=
| Traceback (most recent call last):
|   File "/mnt/c/Users/thore/Desktop/precice/Forschungsprojekt/precice-structure-generator/config-checker/preciceconfigchecker/cli.py", line 9, in <module>
|     from preciceconfigchecker.rules_processing import check_all_rules, print_all_results
|   File "/mnt/c/Users/thore/Desktop/precice/Forschungsprojekt/precice-structure-generator/venv/lib/python3.12/site-packages/preciceconfigchecker/rules_processing.py", line 8, in <module>
|     from preciceconfigchecker.rules import missing_coupling, missing_exchange, data_use_read_write, compositional_coupling
| ModuleNotFoundError: No module named 'preciceconfigchecker.rules'
[Validate Example Configurations/discover-and-test]   ❌  Failure - Main Test CLI of config-checker
```
